Fix Lit Analyzer issues and add to CI/pre-push

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,2 +1,8 @@
 #!/usr/bin/env sh
-yarn analyze
+echo "Running Lit Analyzer..."
+if yarn analyze; then
+  echo "Lit Analyzer passed."
+else
+  echo "Lit Analyzer failed. Please fix the issues before pushing."
+  exit 1
+fi
